#!/usr/bin/env bash

case "$1" in
    "serve")
        scripts/serve.sh
    ;;
    "deploy")
        scripts/deploy.sh
    ;;
    *)
        echo "mbs-cs/learn build tool. This command provides a variety of commands to control the learn build process."
        echo ""
        echo "Commands:"
        echo "  * serve  | Sets up a local environment on which the docs are running on ::8000"
        echo "  * deploy | Deploys the docs to the gh-pages branch and pushes to the 'origin' remote"
    ;;
esac
