site_name: mbs-cs/learn
site_url: https://mbs-cs.github.io/learn
site_description: A collection of documents to aid in learning / revision with the Computer Science GCSE starting 2016.
site_author: Jamie Mansfield

repo_url: https://github.com/mbs-cs/learn
google_analytics: [UA-85004702-1, auto]

remote_branch: gh-pages
remote_name: origin

pages:
    - Home: 'index.md'
    - Data:
        - Home: 'data/index.md'
        - Binary: 'data/binary.md'
        - Denary: 'data/denary.md'
        - Units: 'data/units.md'
    - Hardware:
        - Home: 'hardware/index.md'
        - Motherboard: 'hardware/motherboard.md'
        - CPU:
            - Home: 'hardware/cpu/index.md'
            - Instruction Cycle: 'hardware/cpu/instruction-cycle.md'
        - Memory:
            - Home: 'hardware/memory/index.md'
            - Read-Only Memory: 'hardware/memory/rom.md'
        - Storage:
            - Home: 'hardware/storage/index.md'
            - Solid State:
                - Home: 'hardware/storage/solid-state/index.md'
                - Solid State Drives: 'hardware/storage/solid-state/drives.md'
                - USB Flash Memory: 'hardware/storage/solid-state/flash.md'
    - Programming:
        - Home: 'programming/index.md'
        - Object-Oriented Programming: 'programming/oop.md'
    - Extra:
        - Home: 'extra/index.md'
        - Little Man Computer:
            - Home: 'extra/lmc/index.md'
            - Advanced: 'extra/lmc/advanced.md'
        - Licensing:
            - Home: 'extra/licensing/index.md'
            - GPL Free Documentation License: 'extra/licensing/gpl-free-documentation-license.md'
            - BSD 3-Clause License: 'extra/licensing/bsd-3-clause.md'
