site_name: Learn 2016 Computer Science GCSE
site_url: https://mbs-cs-2016.github.io/learn/
site_description: Documentation for the students taking the Computer Science GCSE starting in 2016.
site_author: Jamie Mansfield

repo_url: https://github.com/mbs-cs-2016/learn

remote_branch: gh-pages
remote_name: origin

pages:
    - Home: 'index.md'
    - CPU:
        - Home: 'cpu/index.md'
        - Instruction Cycle: 'cpu/instruction-cycle.md'
    - Extra:
        - Home: 'extra/index.md'
        - Little Man Computer:
            - Home: 'extra/lmc/index.md'
            - Advanced: 'extra/lmc/advanced.md'
