site_name: mbs-cs-2016/learn
site_url: https://mbs-cs-2016.github.io/learn
site_description: A collection of documents to aid in learning / revision with the Computer Science GCSE starting 2016.
site_author: Jamie Mansfield

repo_url: https://github.com/mbs-cs-2016/learn
google_analytics: [UA-85004702-1, auto]

remote_branch: gh-pages
remote_name: origin

pages:
    - Home: 'index.md'
    - CPU:
        - Home: 'cpu/index.md'
        - Instruction Cycle: 'cpu/instruction-cycle.md'
    - Memory:
        - Home: 'memory/index.md'
        - Read-Only Memory: 'memory/rom.md'
    - Storage:
        - Home: 'storage/index.md'
        - Solid State:
            - Home: 'storage/solid-state/index.md'
            - Solid State Drives: 'storage/solid-state/drives.md'
            - USB Flash Memory: 'storage/solid-state/flash.md'
    - Extra:
        - Home: 'extra/index.md'
        - Little Man Computer:
            - Home: 'extra/lmc/index.md'
            - Advanced: 'extra/lmc/advanced.md'
        - Licensing:
            - Home: 'extra/licensing/index.md'
            - GPL Free Documentation License: 'extra/licensing/gpl-free-documentation-license.md'
            - BSD 3-Clause License: 'extra/licensing/bsd-3-clause.md'
